- name: Manage XCP-ng without Python (raw mode)
  hosts: xen
  gather_facts: no
  become: true

  tasks:
    - name: Connectivity check (raw "pong")
      ansible.builtin.raw: 'echo pong'
      register: pong
      changed_when: false

    - name: Show pong
      ansible.builtin.debug:
        var: pong.stdout
