- name: Update XCP-ng hosts with raw yum
  hosts: xen
  gather_facts: no
  become: true
  strategy: linear
  tasks:
    - name: Run yum update
      ansible.builtin.raw: "yum -y update"
      register: yumout
      changed_when: "'No packages marked for update' not in yumout.stdout"

    - name: Show yum output
      ansible.builtin.debug:
        var: yumout.stdout
