---
- name: Update Rocky Linux hosts
  hosts: rocky
  become: true
  gather_facts: true

  tasks:
    - name: Make sure dnf cache is up to date
      ansible.builtin.dnf:
        update_cache: true

    - name: Update all packages to latest version
      ansible.builtin.dnf:
        name: "*"
        state: latest
      register: dnf_update

    - name: Print summary of updated packages
      ansible.builtin.debug:
        msg: "Updated packages: {{ dnf_update.changes | default({}) }}"
